import type { Metadata } from "next";
import "../globals.css";
import Authenticated from "@/components/providers/conditional/Authenticated";
import BottomNav, { type NavLink } from "@/components/ui/bottom-nav";
import { Home } from "lucide-react";
import NotificationMenuButton from "@/components/ui/notification-menu-btn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navLinks: NavLink[] = [
  {
    name: "Home",
    href: "/",
    icon: <Home />,
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: <NotificationMenuButton />,
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Authenticated>
      <div className="h-screen w-screen relative flex">
        {children}
        <BottomNav links={navLinks} />
      </div>
    </Authenticated>
  );
}
