import type { Metadata } from "next";
import "../globals.css";
import Authenticated from "@/components/providers/conditional/Authenticated";
import BottomNav, { type NavLink } from "@/components/ui/bottom-nav";
import { Home, IdCard, Settings } from "lucide-react";
import NotificationMenuButton from "@/components/ui/notification-menu-btn";
import ThemeSwitch from "@/components/ui/theme-switch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navLinks: NavLink[] = [
  {
    name: "Acceuil",
    href: "/",
    icon: <Home />,
  },
  {
    name: "Accès",
    href: "access-codes",
    icon: <IdCard />,
  },
  {
    name: "Paramètres",
    href: "/settings",
    icon: <Settings />,
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: <NotificationMenuButton />,
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Authenticated>
      <div className="h-screen w-screen relative flex">
        <div className="absolute flex justify-end top-0 right-0 z-30">
          <ThemeSwitch />
        </div>
        {children}
        <BottomNav links={navLinks} />
      </div>
    </Authenticated>
  );
}
